using System;
using System.Collections.Generic;
using System.Text;

namespace Dissonance.Framework.DevIL
{
	partial class IL
	{
		public const int FALSE = 0;
		public const int TRUE = 1;
		public const int VENDOR = 7936;
		public const int LOAD_EXT = 7937;
		public const int SAVE_EXT = 7938;
		public const int VERSION_1_6_7 = 1;
		public const int VERSION = 167;
		public const int ORIGIN_BIT = 1;
		public const int FILE_BIT = 2;
		public const int PAL_BIT = 4;
		public const int FORMAT_BIT = 8;
		public const int TYPE_BIT = 16;
		public const int COMPRESS_BIT = 32;
		public const int LOADFABIT = 64;
		public const int FORMAT_SPECIFIC_BIT = 128;
		public const int ALL_ATTRIB_BITS = 1048575;
		public const int PAL_NONE = 1024;
		public const int PAL_RGB24 = 1025;
		public const int PAL_RGB32 = 1026;
		public const int PAL_RGBA32 = 1027;
		public const int PAL_BGR24 = 1028;
		public const int PAL_BGR32 = 1029;
		public const int PAL_BGRA32 = 1030;
		public const int TYPE_UNKNOWN = 0;
		public const int JASC_PAL = 1141;
		public const int ORIGIN_LOWER_LEFT = 1537;
		public const int ORIGIN_UPPER_LEFT = 1538;
		public const int FILE_OVERWRITE = 1568;
		public const int SAVE_INTERLACED = 1593;
		public const int WU_QUANT = 1601;
		public const int NEU_QUANT = 1602;
		public const int FASTEST = 1632;
		public const int LESS_MEM = 1633;
		public const int DONT_CARE = 1634;
		public const int MEM_SPEED_HINT = 1637;
		public const int USE_COMPRESSION = 1638;
		public const int NO_COMPRESSION = 1639;
		public const int COMPRESSION_HINT = 1640;
		public const int SUB_NEXT = 1664;
		public const int SUB_MIPMAP = 1665;
		public const int SUB_LAYER = 1666;
		public const int COMPRESS_NONE = 1793;
		public const int COMPRESS_RLE = 1794;
		public const int COMPRESS_LZO = 1795;
		public const int COMPRESS_ZLIB = 1796;
		public const int TGA_ID_STRING = 1815;
		public const int TGA_AUTHNAME_STRING = 1816;
		public const int TGA_AUTHCOMMENT_STRING = 1817;
		public const int PNG_AUTHNAME_STRING = 1818;
		public const int PNG_TITLE_STRING = 1819;
		public const int PNG_DESCRIPTION_STRING = 1820;
		public const int TIF_DESCRIPTION_STRING = 1821;
		public const int TIF_HOSTCOMPUTER_STRING = 1822;
		public const int TIF_DOCUMENTNAME_STRING = 1823;
		public const int TIF_AUTHNAME_STRING = 1824;
		public const int CHEAD_HEADER_STRING = 1826;
		public const int DXTC_FORMAT = 1797;
		public const int DXT1 = 1798;
		public const int DXT2 = 1799;
		public const int DXT3 = 1800;
		public const int DXT4 = 1801;
		public const int DXT5 = 1802;
		public const int DXT_NO_COMP = 1803;
		public const int CUBEMAP_POSITIVEX = 1024;
		public const int CUBEMAP_NEGATIVEX = 2048;
		public const int CUBEMAP_POSITIVEY = 4096;
		public const int CUBEMAP_NEGATIVEY = 8192;
		public const int CUBEMAP_POSITIVEZ = 16384;
		public const int CUBEMAP_NEGATIVEZ = 32768;
		public const int SEEK_SET = 0;
		public const int SEEK_CUR = 1;
		public const int SEEK_END = 2;
		public const int EOF = -1;
	}
}
